name: 'Install API Management Operations CLI'
description: 'Install the API Management Operations CLI from GitHub Packages'
inputs:
  token:
    description: 'Token to use for acquiring NPM package'
    required: true
  version:
    description: 'Version of the API Management Operations CLI to install'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cloud-cowboys'

    - name: Authenticate to GitHub Packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.token }}" > ~/.npmrc
        echo "@cloud-cowboys:registry=https://npm.pkg.github.com" >> ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
      shell: bash

    - name: Install NPM package
      run: npm install -g @cloud-cowboys/apimops@${{ inputs.version }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Run NPM package
      run: apimops --version
      shell: bash

